title: Slim Gabsi's Blog
email: slimgabsi287@gmail.com
description: Slim's Blog
author: Slim Gabsi
# baseurl:            "/"
url: "https://slimgabsi.github.io"
theme: jekyll-theme-hacker
<meta name="google-site-verification" content="HNu5FmPIEx5bCXTNW04ymYwRvu4PrctQMv148r2goE8" />
