title: Slim Gabsi's Blog
email: slimgabsi287@gmail.com
description: Slim's Blog
author: Slim Gabsi
url: "https://slimgabsi.github.io"
google-site-verification : HNu5FmPIEx5bCXTNW04ymYwRvu4PrctQMv148r2goE8
theme: jekyll-theme-hacker
